services:
  server:
    image: registry.digitalocean.com/growly/server:latest
    container_name: server
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - pg-db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  pg-db:
    image: postgres:16
    container_name: postgres
    # ports:
    #   - '5432:5432'
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - 'com.github.nginx-proxy.nginx'
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  pg_data:
  redis_data:
  certs:
  vhost:
  html:
  acme:
