services:
  server:
    platform: linux/amd64
    # image: ${REGISTRY:-registry.digitalocean.com/growly}/server:${TAG:-latest}
    image: server:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    env_file:
      - packages/server/.env
    ports:
      - '8080:8080'
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
