name: Suite Format
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Template Install dependencies
        run: pnpm install

      - name: Template Format
        run: pnpm run format
